(function(name,data){
 if(typeof onTileMapLoaded === 'undefined') {
  if(typeof TileMaps === 'undefined') TileMaps = {};
  TileMaps[name] = data;
 } else {
  onTileMapLoaded(name,data);
 }
 if(typeof module === 'object' && module && module.exports) {
  module.exports = data;
 }})("level01",
{ "height":8,
 "infinite":false,
 "layers":[
        {
         "data":[3, 3, 3, 5, 4, 6, 3, 3, 3, 3, 3, 5, 4, 6, 3, 3, 3, 3, 3, 5, 4, 6, 3, 3, 3, 3, 3, 5, 4, 6, 3, 3, 3, 3, 3, 5, 4, 6, 3, 3, 3, 3, 3, 5, 4, 6, 3, 3, 3, 3, 3, 5, 4, 6, 3, 3, 3, 3, 3, 5, 4, 6, 3, 3],
         "height":8,
         "id":1,
         "name":"level01",
         "opacity":1,
         "type":"tilelayer",
         "visible":false,
         "width":8,
         "x":0,
         "y":0
        }, 
        {
         "data":[0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 9, 0, 0, 0, 0],
         "height":8,
         "id":8,
         "name":"level01_marks",
         "opacity":1,
         "type":"tilelayer",
         "visible":false,
         "width":8,
         "x":0,
         "y":0
        }, 
        {
         "data":[2, 2, 2, 1, 3, 5, 4, 6, 2, 2, 2, 1, 3, 5, 4, 6, 2, 2, 2, 1, 3, 5, 4, 6, 1, 1, 1, 1, 3, 5, 4, 6, 3, 3, 3, 3, 3, 5, 4, 6, 3, 3, 3, 3, 3, 5, 4, 6, 3, 3, 3, 3, 3, 5, 4, 6, 3, 3, 3, 3, 3, 5, 4, 6],
         "height":8,
         "id":4,
         "name":"level02",
         "opacity":1,
         "type":"tilelayer",
         "visible":true,
         "width":8,
         "x":0,
         "y":0
        }, 
        {
         "data":[0, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 9, 0, 0],
         "height":8,
         "id":9,
         "name":"level02_marks",
         "opacity":1,
         "type":"tilelayer",
         "visible":true,
         "width":8,
         "x":0,
         "y":0
        }],
 "nextlayerid":10,
 "nextobjectid":4,
 "orientation":"isometric",
 "renderorder":"right-down",
 "tiledversion":"1.2.3",
 "tileheight":64,
 "tilesets":[
        {
         "columns":0,
         "firstgid":1,
         "grid":
            {
             "height":1,
             "orientation":"orthogonal",
             "width":1
            },
         "margin":0,
         "name":"ground",
         "spacing":0,
         "tilecount":9,
         "tileheight":64,
         "tiles":[
                {
                 "id":0,
                 "image":"..\/img\/grass01.png",
                 "imageheight":64,
                 "imagewidth":128
                }, 
                {
                 "id":1,
                 "image":"..\/img\/test3.png",
                 "imageheight":64,
                 "imagewidth":128
                }, 
                {
                 "id":2,
                 "image":"..\/img\/grass02.png",
                 "imageheight":64,
                 "imagewidth":128
                }, 
                {
                 "id":3,
                 "image":"..\/img\/road-center.png",
                 "imageheight":64,
                 "imagewidth":128
                }, 
                {
                 "id":4,
                 "image":"..\/img\/road-left.png",
                 "imageheight":64,
                 "imagewidth":128
                }, 
                {
                 "id":5,
                 "image":"..\/img\/road-right.png",
                 "imageheight":64,
                 "imagewidth":128
                }, 
                {
                 "id":6,
                 "image":"..\/img\/exit-tile.png",
                 "imageheight":64,
                 "imagewidth":128,
                 "properties":[
                        {
                         "name":"map_mark",
                         "type":"string",
                         "value":"finish"
                        }]
                }, 
                {
                 "id":7,
                 "image":"..\/img\/enemy-tile.png",
                 "imageheight":64,
                 "imagewidth":128,
                 "properties":[
                        {
                         "name":"map_mark",
                         "type":"string",
                         "value":"enemy"
                        }]
                }, 
                {
                 "id":8,
                 "image":"..\/img\/start-tile.png",
                 "imageheight":64,
                 "imagewidth":128,
                 "properties":[
                        {
                         "name":"map_mark",
                         "type":"string",
                         "value":"start"
                        }]
                }],
         "tilewidth":128
        }],
 "tilewidth":128,
 "type":"map",
 "version":1.2,
 "width":8
});